services:
  database:
    image: postgres:15.3-alpine
    container_name: todo-db
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: todouser
      POSTGRES_PASSWORD: todopass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/todoapp
      - SPRING_DATASOURCE_USERNAME=todouser
      - SPRING_DATASOURCE_PASSWORD=todopass
    depends_on:
      - database
    networks:
      - todo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge